In [2]:
import numpy as np

# Creating a 1D/2D list with numpy

## Zeros, Ones, and Eye

In [10]:
A = np.zeros((10,3)) #Generates a list of 0's of (size) (Generated as a 1d list)

B = np.ones(10) #Generates a list of (size) full of 1's (Generated as a 1d list)

#Both can take (row,column) as a parameter

C = np.ones((2,2)) #Generates 2D array

print('C: ',C)
print("A: ",A)
print("B: ",B)

np.eye(5) #Generates a list of (size x size) with ones generating diagonal and the rest zero (2d lists)

C:  [[1. 1.]
 [1. 1.]]
A:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
B:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Create a numpy list using a python list

In [11]:
python_list = [1,2,3]
numpyList = np.array(python_list)

print(numpyList)
print(type(numpyList))

[1 2 3]
<class 'numpy.ndarray'>


## Create a numpy list using numpy

In [5]:
list_A = np.arange(1,17,2) #arange has the parameters (start, stop, increments)
print(list_A)

[ 1  3  5  7  9 11 13 15]


### CHALLENGE 1: CREATE A LIST 


In [4]:
# Create a list using numpy or converting from python to numpy
df = np.arange(0,10)

print(df)

[0 1 2 3 4 5 6 7 8 9]


## Making 2D lists using .reshape() and .resize()

In [6]:
list_A = list_A.reshape(4,2) #parameters are (rows,columns)(row*column must = totals values in the list)

print(list_A)

#Finding the rows and columns
np.shape(list_A)

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


(4, 2)

In [8]:
np.resize(list_A,(2,2)) #Like reshape, but list length to fit dimensions

array([[1, 3],
       [5, 7]])

## Making 3D lists

In [8]:
list_A = list_A.reshape(2,2,2)

print(list_A)
np.shape(list_A)

[[[ 1  3]
  [ 5  7]]

 [[ 9 11]
  [13 15]]]


(2, 2, 2)

## Generating random values for a list

In [9]:
#random.rand(size) will produce values of [0,1)
#random.randn(size) will produce values of normal distribution
#random.randint(low, high, size)

listEX = np.random.randn(10)

print(listEX)

random = np.random

listEX = random.randint(0,100,15).reshape(5,3)
print(listEX)

[ 0.39995765 -0.2080579   0.88226864  0.77098302 -1.25926327 -0.1131208
 -0.54375928 -0.33613475 -1.34164043 -0.94680055]
[[20 25 40]
 [16 41  9]
 [ 8 85 13]
 [79 32 20]
 [25 92 60]]


### Challenge 2: Make a 2d list 

In [10]:
c2 = np.random.randint(0,10,6)
c2 = c2.reshape(2,3)
print(c2)

[[6 1 7]
 [4 3 3]]


# Filtering and indexing(a value and its position)

## Sorting

In [11]:
print(listEX)
listEX.sort() #sorts lists 
print(listEX)

[[20 25 40]
 [16 41  9]
 [ 8 85 13]
 [79 32 20]
 [25 92 60]]
[[20 25 40]
 [ 9 16 41]
 [ 8 13 85]
 [20 32 79]
 [25 60 92]]


## Finding the min/max and their positions

In [12]:
print(listEX)

print(listEX.min()) #Finding the lowest value
print(listEX.argmin()) #Finding the lowest values position 

print(listEX.max()) #Finding the highest value
print(listEX.argmax()) #Finds the highest values position

[[20 25 40]
 [ 9 16 41]
 [ 8 13 85]
 [20 32 79]
 [25 60 92]]
8
6
92
14


## Filtering values (Using np.where())

In [13]:
#parameters are (condition, condition met, condition not met)

np.where(listEX % 2==0, 1, 2)

#Change the condition not met to the list name

np.where(listEX%2 == 0, 1, listEX) 

#condition not met  = listEX will keep the values that dont meet the condition

array([[ 1, 25,  1],
       [ 9,  1, 41],
       [ 1, 13, 85],
       [ 1,  1, 79],
       [25,  1,  1]])

### Challenge 3: Using the randomized list, find the min value, change it to 0, keep the rest

In [17]:
listR = np.random.randint(0,100,7)
print(listR)
listR = np.where(listR == listR.min(), 0, listR)
print(listR)

[82 96 18 71 61 14 27]
[82 96 18 71 61  0 27]


## Indexing 1D arrays

In [14]:
listC = random.randint(0,100,5)

print(listC[0:2])
listC[0:2] = 20
print(listC)



[15 92]
[20 20 96 12 70]


## 2D indexing


In [15]:
print(listEX[0,0]) #grabs the value in the first row and column
print(listEX[0:3, 1:2]) #grabs the values in the first three rows and second column

17
[[21]
 [52]
 [25]]


## Boolean Indexing

In [18]:
listEX % 2 == 0 #replaces values with True or False

print((listEX % 2 == 0).sum()) #adds up all values that make the statement true

#indexing with booleans

listEX[listEX % 2 == 0] #Filter out false values, leaving only true values

8


array([20, 40, 16,  8, 20, 32, 60, 92])

### Challenge 4: 

array([[195,  10,  11,  60],
       [108, 174, 109,  59],
       [161, 168,  59,   6],
       [ 16,  56,  73, 180]])

# Mean, Median, Mode, and Standard Deviation

## Mean

In [5]:
np.mean(listEX) #Finds the average of the given list


np.float64(58.733333333333334)

## Median

In [19]:
#Finds the value in the middle of the list (No sorting needed)

print(np.median(listEX))



print(listEX)

25.0
[[20 25 40]
 [ 9 16 41]
 [ 8 13 85]
 [20 32 79]
 [25 60 92]]


## Standard Deviation

In [ ]:
np.std(listEX) #How far (on average) values are from the mean

# Revisiting Matrices

In [13]:
#np.matmul takes parameters(list 1, list 2)

C = random.randint(0,100,18).reshape(9,2)
print(C)

D = random.randint(0,100,18).reshape(2,9)
print(D)

np.matmul(C,D)

[[51 78]
 [32 41]
 [98 17]
 [19 27]
 [44 49]
 [65 49]
 [97 91]
 [77  7]
 [31 43]]
[[83 87 91 83 26 57 97 55 32]
 [18 21 57 19 24 10 83 69 35]]


array([[ 5637,  6075,  9087,  5715,  3198,  3687, 11421,  8187,  4362],
       [ 3394,  3645,  5249,  3435,  1816,  2234,  6507,  4589,  2459],
       [ 8440,  8883,  9887,  8457,  2956,  5756, 10917,  6563,  3731],
       [ 2063,  2220,  3268,  2090,  1142,  1353,  4084,  2908,  1553],
       [ 4534,  4857,  6797,  4583,  2320,  2998,  8335,  5801,  3123],
       [ 6277,  6684,  8708,  6326,  2866,  4195, 10372,  6956,  3795],
       [ 9689, 10350, 14014,  9780,  4706,  6439, 16962, 11614,  6289],
       [ 6517,  6846,  7406,  6524,  2170,  4459,  8050,  4718,  2709],
       [ 3347,  3600,  5272,  3390,  1838,  2197,  6576,  4672,  2497]])

# Basic math

In [10]:
C = np.arange(0,10).reshape(2,5)
D = np.arange(10,20).reshape(2,5)

print(f'C*D = \n{C*D}\n')
print(f'C/D = \n{C/D}\n')
print(f'C-D = \n{C-D}\n')
print(f'C+D = \n{C+D}\n')

C*D = 
[[  0  11  24  39  56]
 [ 75  96 119 144 171]]

C/D = 
[[0.         0.09090909 0.16666667 0.23076923 0.28571429]
 [0.33333333 0.375      0.41176471 0.44444444 0.47368421]]

C-D = 
[[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]

C+D = 
[[10 12 14 16 18]
 [20 22 24 26 28]]



In [11]:
np.exp(C)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [23]:
np.sqrt(C)

array([[3.16227766, 1.41421356, 3.        , 2.64575131, 3.31662479],
       [3.46410162, 1.73205081, 3.        , 3.16227766, 2.82842712]])

In [24]:
np.log(D)

array([[1.79175947, 2.48490665, 2.19722458, 1.09861229, 1.79175947],
       [0.        ,       -inf, 0.        , 0.69314718, 0.69314718]])

# Broadcasting and Scalars

## Broadcasting

In [22]:
#Broadcasting is how do you do math when list shapes don't match
#Requirements: Dimensions MUST be == to each other or 1

One = np.ones((4,1))

arr = np.arange(1,4)

print("ones ", One)
print("arr ", arr)

One*arr
One+arr

ones  [[1.]
 [1.]
 [1.]
 [1.]]
arr  [1 2 3]


array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

## Scalars/Scalar Broadcasting

In [40]:
#Scalars are the values themselves, (Think of single #'s)
#Scalar Broadcasting is just multiplying values in a list  

pylist = [1,2,3]

Scalar = 2

list_B = np.array([1,2,3])

print(Scalar * list_B)
print(Scalar * pylist)


[2 4 6]
[1, 2, 3, 1, 2, 3]


In [23]:
arr = np.array([[1,2],[2,3],[3,2]])
arr + np.ones((3,2))

array([[2., 3.],
       [3., 4.],
       [4., 3.]])